### ISSUE TITLE
Unable to use NDigidoc from a strongly-named assembly

### ISSUE THREAD

**Issue by anttikes** [open-eid/ndigidoc#1]
Hello,

I encountered a situation where I attempted to reference NDigidoc library from an executable assembly that uses strong-naming. It was possible to add a reference, but during execution an exception was thrown due to the NDigidoc library itself lacking a strong name.

I used the official installer available from http://www.id.ee/index.php?id=35857.

**Comment by markus-kullerkup** [comment]
We'd like to inform you that our support for "NDigidoc" library has ended in 05.2015.
